### ISSUE TITLE
Condivisione fb

### ISSUE THREAD

**Issue by lucapolez** [Davide95/Editor-Octagone#10]
Nello spazio sotto il tasto download ci vedrei bene un tasto fb per la condivisione sul social del link all'editor.

**Comment by Davide95** [comment]
Ho implementato il tasto condividi su Facebook  (commit 0579e3fa833ebb21b541cef80664900ea1890911) centrato in basso su ogni pagina, credo che così sia il più uniforme possibile. Fammi sapere se ti piace
