### ISSUE TITLE
frecce e fb

### ISSUE THREAD

**Issue by lucapolez** [Davide95/Editor-Octagone#14]
L'immagine della seconda freccia é diversa nell'anteprima.
fb share dovrebbe essere più grande
Da mobile share non funziona
Serirabbe indicazione del formato immagine ammesso ed il messaggio che evidenza l'eventuale errore di inserimento 

Ciao

**Comment by Davide95** [comment]
Anteprima freccia aggiornata con il commit 088469772e12fbef2d4e73c5138eda552650f62e
Se è possibile le prossime volte riesci ad aprirmi un'issue per ogni problema? In modo da tenere separate le discussioni. Grazie

**Comment by Davide95** [comment]
Per quanto riguarda il bottone "condividi" è la dimensione maggiore che Facebook propone

**Comment by Davide95** [comment]
Ho testato il pulsante condividi sul mio cellulare e non sembrano esserci problemi. Farò altri test su altri cellulari il prima possibile

**Comment by Davide95** [comment]
Per quanto riguarda il formato che non è un'immagine da qui tutto sembra funzionare. Chiudo e apro un'issue a parte per il tasto condividi
