### ISSUE TITLE
testo per condivisione editor scudi

### ISSUE THREAD

**Issue by lucapolez** [Davide95/Editor-Octagone#33]
IL TESTO POTREBBE ESSERE IL SEGUENTE:
Ciao!
Questa a sinistra é Molly
e tu quali immagini hai deciso di inserire 
nei tuoi scudi?

I ritorni a capo non sono casuali.

**Comment by Davide95** [comment]
Ciao:)
Per me il testo può andare bene, anche se poco efficace per attirare i visitatori (mia opinione).
Quando apri un issue ricordati di andare su "Projects" come avevo detto le prossime volte, grazie:)
Non sono compilate nemmeno le Labels e non mi hai assegnato l'issue, ho trovato il messaggio per caso
Sposto la discussione su #34
