### ISSUE TITLE
visualizzazione testo in finestra condivisione fb

### ISSUE THREAD

**Issue by lucapolez** [Davide95/Editor-Octagone#38]
il titolo che appare é Roctary (corretto) mentre il testo resta quello di prima.

**Comment by Davide95** [comment]
Mi serve il nuovo testo altrimenti non riesco ad aggiornarlo, grazie

**Comment by lucapolez** [comment]
Testo: octagone digital factory, dalle tue immagini al tuo octagone.

Grazie

**Comment by Davide95** [comment]
Ti confermo che il testo era già aggiornato. Deve esserci qualche problema con il tuo profilo Facebook
