### ISSUE TITLE
Errore nell'immagine di sfondo orizzontale

### ISSUE THREAD

**Issue by lucapolez** [Davide95/Editor-Octagone#4]
Quando un'immagine è più larga che alta viene ruotata

**Comment by Davide95** [comment]
Ho controllato l'immagine che mi hai inviato.
Il problema nasce perché dalle preferenze della tua immagine l'ortientamento indicato è ruotato.
Quando lo apri con chrome lo rileva e lo gira, mentre quando lo apri con l'anteprima immagine non è ruotato.
Il problema non è nell'app a quanto pare ma nel software che edita le foto / nel software della fotocamera
