### ISSUE TITLE
box d'apertura

### ISSUE THREAD

**Issue by lucapolez** [Davide95/Editor-Octagone#8]
Inserire un box di testo in apertura per spiegare quanti e quali elementi salvare. Possibilità di eliminarlo per il futuro

**Comment by Davide95** [comment]
Inserito un alert iniziale. Resto in attesa del testo da inserirci

**Comment by Davide95** [comment]
Ho ricevuto per mail il testo da inserire ed ho applicato il tutto alla demo che puoi vedere al solito link.
Ti chiedo di mantenere questo come unico canale per le discussioni, altrimenti usarne più di uno rende confusionario l'organizzarci
