### ISSUE TITLE
box info

### ISSUE THREAD

**Issue by lucapolez** [Davide95/Editor-Octagone#9]
Il testo che vorrei vedere nel box info é il seguente:

Info

Per giocare a Octagone devi creare:
- 6 scudi per ciascuno dei sette colori di cornice proposti (42 scudi in totale)
- un piano di gioco.

Per il regolamento completo clicca qui.

il link attualmente non mi manda da nessuna parte, l'indirizzo corretto é:
http://www.octagone.org/regolamento-gioco/

Per distinguerlo completamente dall'editor il box lo farei con sfondo giallo.

Grazie

Ciao
Luca

Per l'editazione del testo sostituirei il termine "zoom" con " dimensione font"
e i tasti li porterei sopra alla tavolozza dei colori-testo.

**Comment by Davide95** [comment]
Ciao, effettuo le modifiche il prima possibile.
Per il colore del box eviterei, perché il giallo è il colore degli alert (ovvero tutti gli eventuali problemi).
L'azzurro scuro è il colore per le info di default, renderebbe confusionario all'utente il tutto.

**Comment by Davide95** [comment]
Ho apportato le modifiche, se ti vanno bene fammelo sapere qui che chiudo il thread

**Comment by lucapolez** [comment]
Manca solo di spostare la tavolozza di testo sotto lo zoom.
Grazie

Ciao

**Comment by Davide95** [comment]
Fatto con il commit dd6603fdccb80e82494e53a350648715abb14427
